sudo: required
services:
  - docker

before_install:
  - docker build -t meetgodhani/sample-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true meetgodhani/sample-docker npm test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-935446282602"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"